name_to_id = {
	"archers":'26000001',
	"arrows":'28000001',
	"babydragon":'26000015',
	"balloon":'26000006',
	"bandit":'26000046',
	"barbarianhut":'27000005',
	"barbarians":'26000008',
	"bats":'26000049',
	"battleram":'26000036',
	"bomber":'26000013',
	"bombtower":'27000004',
	"bowler":'26000034',
	"cannon":'27000000',
	"cannoncart":'26000054',
	"clone":'28000013',
	"darkprince":'26000027',
	"dartgoblin":'26000040',
	"electrowizard":'26000042',
	"elitebarbarians":'26000043',
	"elixircollector":'27000007',
	"executioner":'26000045',
	"fireball":'28000000',
	"firespirits":'26000031',
	"flyingmachine":'26000057',
	"freeze":'28000005',
	"furnace":'27000010',
	"giant":'26000003',
	"giantskeleton":'26000020',
	"goblinbarrel":'28000004',
	"goblingang":'26000041',
	"goblinhut":'27000001',
	"goblins":'26000002',
	"golem":'26000009',
	"graveyard":'28000010',
	"guards":'26000025',
	"heal":'28000016',
	"hogrider":'26000021',
	"icegolem":'26000038',
	"icespirit":'26000030',
	"icewizard":'26000023',
	"infernodragon":'27000003',
	"infernotower":'26000037',
	"knight":'26000000',
	"lavahound":'26000029',
	"lightning":'28000007',
	"lumberjack":'26000035',
	"megaknight":'26000055',
	"megaminion":'26000039',
	"miner":'26000032',
	"minionhorde":'26000022',
	"minions":'26000005',
	"minipekka":'26000018',
	"mirror":'28000006',
	"mortar":'27000002',
	"musketeer":'26000014',
	"nightwitch":'26000048',
	"pekka":'26000004',
	"poison":'28000009',
	"prince":'26000016',
	"princess":'26000026',
	"rage":'28000002',
	"rocket":'28000003',
	"royalgiant":'26000024',
	"skeletonarmy":'26000012',
	"skeletonbarrel":'',
	"skeletons":'26000010',
	"sparky":'26000033',
	"speargoblins":'26000019',
	"tesla":'27000006',
	"thelog":'28000011',
	"threemusketeers":'26000028',
	"tombstone":'27000009',
	"tornado":'28000012',
	"valkyrie":'26000011',
	"witch":'26000007',
	"wizard":'26000017',
	"xbow":'27000008',
	"zap":'28000008',
}
cards_abbrev = {
	'archers': 'archers',
	'arch': 'archers',
	'arrows': 'arrows',
	'arrow': 'arrows',
	'arr': 'arrows',
	'baby-dragon': 'babydragon',
	'bbd': 'babydragon',
	'babyd': 'babydragon',
	'bd': 'babydragon',
	'babydragon': 'babydragon',
	'balloon': 'balloon',
	'loon': 'balloon',
	'bandit': 'bandit',
	'barbarian-hut': 'barbarianhut',
	'barb-hut': 'barbarianhut',
	'bh': 'barbarianhut',
	'barbarianhut': 'barbarianhut',
	'barbarians': 'barbarians',
	'barb': 'barbarians',
	'barbs': 'barbarians',
	'bats': 'bats',
	'bat': 'bats',
	'battle-ram': 'battleram',
	'br': 'battleram',
	'ram': 'battleram',
	'battleram': 'battleram',
	'bomb-tower': 'bombtower',
	'bt': 'bombtower',
	'bombtower': 'bombtower',
	'bomber': 'bomber',
	'bowler': 'bowler',
	'cannon': 'cannon',
	'cannon-cart': 'cannoncart',
	'cc': 'cannoncart',
	'cart': 'cannoncart',
	'cannoncart': 'cannoncart',
	'clone': 'clone',
	'dark-prince': 'darkprince',
	'dp': 'darkprince',
	'dank-prince': 'darkprince',
	'darkprince': 'darkprince',
	'dart-goblin': 'dartgoblin',
	'dg': 'dartgoblin',
	'dart-gob': 'dartgoblin',
	'dart-gobs': 'dartgoblin',
	'dartgoblin': 'dartgoblin',
	'electro-wizard': 'electrowizard',
	'ew': 'electrowizard',
	'ewiz': 'electrowizard',
	'ewizard': 'electrowizard',
	'electrowizard': 'electrowizard',
	'elite-barbarians': 'elitebarbarians',
	'eb': 'elitebarbarians',
	'ebarb': 'elitebarbarians',
	'ebarbs': 'elitebarbarians',
	'elitebarbarians': 'elitebarbarians',
	'elixir-collector': 'elixircollector',
	'ec': 'elixircollector',
	'pump': 'elixircollector',
	'collector': 'elixircollector',
	'elixircollector': 'elixircollector',
	'executioner': 'executioner',
	'ex': 'executioner',
	'exe': 'executioner',
	'exec': 'executioner',
	'fire-spirits': 'firespirits',
	'fs': 'firespirits',
	'firespirits': 'firespirits',
	'fireball': 'fireball',
	'fb': 'fireball',
	'flying-machine': 'flyingmachine',
	'fm': 'flyingmachine',
	'fly': 'flyingmachine',
	'machine': 'flyingmachine',
	'flyingmachine': 'flyingmachine',
	'freeze': 'freeze',
	'furnace': 'furnace',
	'giant-skeleton': 'giantskeleton',
	'gs': 'giantskeleton',
	'giantskeleton': 'giantskeleton',
	'giant': 'giant',
	'goblin-barrel': 'goblinbarrel',
	'gb': 'goblinbarrel',
	'gob-barrel': 'goblinbarrel',
	'barrel': 'goblinbarrel',
	'goblinbarrel': 'goblinbarrel',
	'goblin-gang': 'goblingang',
	'gg': 'goblingang',
	'gob-gang': 'goblingang',
	'gang': 'goblingang',
	'goblingang': 'goblingang',
	'goblin-hut': 'goblinhut',
	'gob-hut': 'goblinhut',
	'gh': 'goblinhut',
	'goblinhut': 'goblinhut',
	'goblins': 'goblins',
	'gobs': 'goblins',
	'gob': 'goblins',
	'stab-gobs': 'goblins',
	'stab-gob': 'goblins',
	'golem': 'golem',
	'graveyard': 'graveyard',
	'gy': 'graveyard',
	'skillyard': 'graveyard',
	'guards': 'guards',
	'heal': 'heal',
	'hog-rider': 'hogrider',
	'hog': 'hogrider',
	'hogrider': 'hogrider',
	'ice-golem': 'icegolem',
	'ig': 'icegolem',
	'icegolem': 'icegolem',
	'ice-spirit': 'icespirit',
	'is': 'icespirit',
	'icespirit': 'icespirit',
	'ice-wizard': 'icewizard',
	'iw': 'icewizard',
	'ice-wiz': 'icewizard',
	'iwiz': 'icewizard',
	'icewizard': 'icewizard',
	'inferno-dragon': 'infernodragon',
	'id': 'infernodragon',
	'infernodragon': 'infernodragon',
	'inferno-tower': 'infernotower',
	'inferno': 'infernotower',
	'it': 'infernotower',
	'infernotower': 'infernotower',
	'knight': 'knight',
	'lava-hound': 'lavahound',
	'lava': 'lavahound',
	'lh': 'lavahound',
	'hound': 'lavahound',
	'lavahound': 'lavahound',
	'lightning': 'lightning',
	'lumberjack': 'lumberjack',
	'lj': 'lumberjack',
	'mega-knight': 'megaknight',
	'mk': 'megaknight',
	'mknight': 'megaknight',
	'megaknight': 'megaknight',
	'mega-minion': 'megaminion',
	'mm': 'megaminion',
	'meta-minion': 'megaminion',
	'mega': 'megaminion',
	'megaminion': 'megaminion',
	'miner': 'miner',
	'mini-pekka': 'minipekka',
	'minip': 'minipekka',
	'mini-p': 'minipekka',
	'mp': 'minipekka',
	'minipekka': 'minipekka',
	'minion-horde': 'minionhorde',
	'mh': 'minionhorde',
	'horde': 'minionhorde',
	'minionhorde': 'minionhorde',
	'minions': 'minions',
	'mirror': 'mirror',
	'mortar': 'mortar',
	'musketeer': 'musketeer',
	'1m': 'musketeer',
	'musk': 'musketeer',
	'night-witch': 'nightwitch',
	'nwitch': 'nightwitch',
	'nw': 'nightwitch',
	'nightwitch': 'nightwitch',
	'pekka': 'pekka',
	'poison': 'poison',
	'prince': 'prince',
	'princess': 'princess',
	'rage': 'rage',
	'rocket': 'rocket',
	'royal-giant': 'royalgiant',
	'rg': 'royalgiant',
	'rgg': 'royalgiant',
	'royalgiant': 'royalgiant',
	'skeleton-army': 'skeletonarmy',
	'skarmy': 'skeletonarmy',
	'sa': 'skeletonarmy',
	'skeletonarmy': 'skeletonarmy',
	'skeleton-barrel': 'skeletonbarrel',
	'sbarrel': 'skeletonbarrel',
	'sb': 'skeletonbarrel',
	'skeletonbarrel': 'skeletonbarrel',
	'skeletons': 'skeletons',
	'skele': 'skeletons',
	'skeles': 'skeletons',
	'sparky': 'sparky',
	'spear-goblins': 'speargoblins',
	'spear-gobs': 'speargoblins',
	'spear-gob': 'speargoblins',
	'sgobs': 'speargoblins',
	'sgob': 'speargoblins',
	'speargoblins': 'speargoblins',
	'tesla': 'tesla',
	'the-log': 'thelog',
	'log': 'thelog',
	'thelog': 'thelog',
	'three-musketeers': 'threemusketeers',
	'3m': 'threemusketeers',
	'3musk': 'threemusketeers',
	'3musks': 'threemusketeers',
	'threemusketeers': 'threemusketeers',
	'tombstone': 'tombstone',
	'ts': 'tombstone',
	'tornado': 'tornado',
	'nado': 'tornado',
	'valkyrie': 'valkyrie',
	'valk': 'valkyrie',
	'witch': 'witch',
	'wizard': 'wizard',
	'wiz': 'wizard',
	'xbow': 'xbow',
	'x-bow': 'xbow',
	'zap': 'zap',
}
deckurl = 'https://link.clashroyale.com/deck/en?deck='

def copylink(cards): 
	"""converts list of cards into ids,
	compiles list of ids into url
	"""
	cards = list(map(lambda x: cards_abbrev[x], cards))
	cardids = list(map(lambda x: name_to_id[x], cards))
	url = deckurl + ';'.join(cardids)
	return url

cards = input('cards?\n')
cards = cards.strip().split()
print("\n\n{}".format(copylink(cards)))
input()